# Generated by Django 5.1.1 on 2024-09-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('full_address', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('website', models.URLField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.city')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.city')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.CharField(blank=True)),
                ('sex', models.CharField(blank=True)),
                ('special_needs', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.city')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.shelter')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.species')),
            ],
        ),
    ]
