# Generated by Django 5.1.1 on 2024-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=models.ImageField(default='none', upload_to='images/'),
            preserve_default=False,
        ),
    ]
